# Generated by Django 5.1.1 on 2024-11-06 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FeederRegistro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('feeder_id', models.IntegerField()),
                ('feeder_name', models.CharField(max_length=255)),
                ('feeder_code', models.CharField(max_length=50)),
                ('color_feeder', models.CharField(max_length=50)),
                ('color_semana', models.CharField(max_length=50)),
                ('tecnico', models.CharField(max_length=50)),
                ('tiempo_captura', models.IntegerField()),
                ('observaciones', models.TextField()),
                ('tiempo', models.CharField(max_length=20)),
                ('CP', models.CharField(default='NG', max_length=10)),
                ('QP', models.CharField(default='NG', max_length=10)),
                ('HOVER', models.CharField(default='NG', max_length=10)),
                ('BFC', models.CharField(default='NG', max_length=10)),
                ('fecha_mantenimiento', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
