# Generated by Django 5.1.1 on 2024-11-06 01:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantto_feeder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feederregistro',
            name='fecha_mantenimiento',
            field=models.DateField(max_length=10),
        ),
    ]
