# Generated by Django 5.1.2 on 2024-11-25 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantto_feeder', '0002_alter_feederregistro_fecha_mantenimiento'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cronometro',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tiempo_inicio', models.DateTimeField(blank=True, null=True)),
                ('tiempo_fin', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
