# Generated by Django 5.1.2 on 2024-11-26 00:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantto_feeder', '0003_cronometro'),
    ]

    operations = [
        migrations.AddField(
            model_name='cronometro',
            name='feeder_id',
            field=models.CharField(default='default_feeder_id', max_length=255),
        ),
        migrations.AlterField(
            model_name='cronometro',
            name='tiempo_inicio',
            field=models.DateTimeField(),
        ),
    ]
