# Generated by Django 5.1.2 on 2024-12-12 19:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mantto_feeder', '0006_alter_cronometro_feeder_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='feederregistro',
            old_name='created_at',
            new_name='fecha_creacion',
        ),
    ]
