# Generated by Django 5.1.2 on 2025-04-03 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantto_feeder', '0008_partesfeeder'),
    ]

    operations = [
        migrations.AddField(
            model_name='partesfeeder',
            name='estado',
            field=models.CharField(default='Disponible', max_length=50),
        ),
        migrations.AddField(
            model_name='partesfeeder',
            name='stock_minimo',
            field=models.IntegerField(default=0),
        ),
    ]
