# Generated by Django 5.1.2 on 2025-04-08 17:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mantto_feeder', '0010_feederparareparar'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartesRequeridas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no_part', models.CharField(max_length=50)),
                ('nombre', models.CharField(max_length=255)),
                ('costo', models.DecimalField(decimal_places=2, max_digits=10)),
                ('cantidad', models.IntegerField()),
                ('feeder_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mantto_feeder.feederparareparar')),
            ],
        ),
    ]
